---
- name: Disable ports on HP ProCurve switches
  hosts: '*'
  gather_facts: no
  become: no
  vars:
    switch_username: "{{ lookup('env', 'switch_username') }}"
    switch_password: "{{ lookup('env', 'switch_password') }}"
    port_input: "{{ lookup('env', 'port_input') | default('1-4') }}"
    ansible_connection: ssh
    ansible_user: switch_username
    ansible_password: switch_password
    ansible_ssh_common_args: >-
      -o KexAlgorithms=+diffie-hellman-group14-sha1
      -o HostKeyAlgorithms=+ssh-rsa
      -o PubkeyAcceptedKeyTypes=+ssh-rsa

  tasks:
    - name: Set port list based on input
      set_fact:
        port_list: >-
          {{ 
            ([port_input | int]) if '-' not in port_input else 
            range(port_input.split('-')[0] | int, port_input.split('-')[1] | int + 1) | list
          }}

    - name: Show switch and user
      debug:
        msg: "Connecting to {{ inventory_hostname }} with username: {{switch_username }}"
    
    - name: Show password length
      debug:
        msg: "Password length: {{ switch_password | length }}"

    - name: Disable each port
      ansible.builtin.shell: |
        echo "{{ switch_password }}" | sshpass -p '{{ switch_password }}' ssh -o StrictHostKeyChecking=no {{ switch_username }}@{{ inventory_hostname }} <<EOF
        configure
        interface {{ item }}
        disable
        exit
        exit
        write memory
        EOF
      loop: "{{ port_list }}"