- name: Check Raspberry Pi Reachability
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping device
      ping:
      register: ping_result
      ignore_unreachable: yes
      failed_when: false

    - name: Mark as reachable
      set_fact:
        is_reachable: true
      when: not ping_result.failed

- name: Healthcheck Summary
  hosts: localhost
  gather_facts: no
  vars:
    all_hosts: "{{ groups['all'] }}"
    reachable_hosts: >-
      {{
        all_hosts |
        selectattr('is_reachable', 'defined') |
        list
      }}
    unreachable_hosts: "{{ all_hosts | difference(reachable_hosts) }}"
  tasks:
    - name: Show Summary
      debug:
        msg: |
          ✅ Reachable Pis: {{ reachable_hosts | sort }}
          ❌ Unreachable Pis: {{ unreachable_hosts | sort }}
