- name: Raspberry Pi Health Check
  hosts: all
  gather_facts: yes
  ignore_unreachable: yes

  tasks:
    - name: Mark this host as reachable
      set_fact:
        is_reachable: true

- name: Healthcheck Summary
  hosts: localhost
  gather_facts: no
  vars:
    all_hosts: "{{ groups['all'] }}"
    reachable_hosts: >-
      {{
        all_hosts |
        selectattr('is_reachable', 'defined') |
        list
      }}
    unreachable_hosts: "{{ all_hosts | difference(reachable_hosts) }}"
  tasks:
    - name: Show Summary
      debug:
        msg: |
          ✅ Reachable Pis: {{ reachable_hosts | sort }}
          ❌ Unreachable Pis: {{ unreachable_hosts | sort }}