---
- name: Healthcheck
  hosts: '*'
  gather_facts: yes
  become_user: root

  tasks:
    - name: Check if host is reachable
      ping:
      register: ping_result
      ignore_errors: yes

    - name: Skip play if unreachable
      meta: end_play
      when: ping_result is failed


    - name: Uptime
      command: uptime -p
      register: uptime_output

    - name: Disk Usage
      command: df -h /
      register: disk_output
    
    - name: Memory Usage
      command: free -h
      register: memory_output

    - name: CPU Load
      command: cat /proc/loadavg
      register: load_output

    - name: CPU Temp
      command: vcgencmd measure_temp
      register: temp_output
      ignore_errors: yes

    - name: Print Health Info
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Uptime: {{ uptime_output.stdout }}
          Disk: {{ disk_output.stdout_lines[1] }}
          Memory: {{ memory_output.stdout_lines[1] }}
          Load Avg: {{ load_output.stdout }}
          Temp: {{ temp_output.stdout | default('Not available') }}