- name: Raspberry Pi Health Check
  hosts: all
  gather_facts: yes
  ignore_unreachable: yes  # This is key to keep going if a host is down
  any_errors_fatal: false

  tasks:
    - name: Add reachable host to success list
      set_fact:
        reachable_hosts: "{{ reachable_hosts | default([]) + [inventory_hostname] }}"

- name: Log Unreachable Hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Add unreachable host to failure list
      set_fact:
        unreachable_hosts: "{{ unreachable_hosts | default([]) + [inventory_hostname] }}"
      when: ansible_facts is not defined  # fallback if gather_facts failed

- name: Summary Report
  hosts: localhost
  gather_facts: no
  vars:
    reachable_hosts: "{{ hostvars | dict2items | selectattr('value.reachable_hosts', 'defined') | map(attribute='value.reachable_hosts') | flatten | unique }}"
    unreachable_hosts: "{{ groups['all'] | difference(reachable_hosts) }}"
  tasks:
    - name: Show Summary
      debug:
        msg: |
          ✅ Reachable Pis: {{ reachable_hosts | sort }}
          ❌ Unreachable Pis: {{ unreachable_hosts | sort }}
